package flecs

FLECS_DEBUG :: #config(FLECS_DEBUG, false)
FLECS_USE_OS_ALLOC :: #config(FLECS_USE_OS_ALLOC, false)
FLECS_SANITIZE :: #config(FLECS_SANITIZE, false)
FLECS_TERM_COUNT_MAX :: #config(FLECS_TERM_COUNT_MAX, 32)
FLECS_SCRIPT :: #config(FLECS_SCRIPT, true)

